VERSION="2.1.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
  "GATWCHLKROX6LB2UJ6JM5VKMLLUKKQ5II6MAHFCKCEU47OYGIOENFAIL",
  "GBMDWLCULO2K6CDBK5RIRWUPOWFPOP3CQN5FFQS3Z6HVLD2FZYI4FAIL"
]

[DOCUMENTATION]
ORG_NAME="The KaleFail Project"
ORG_URL="https://kalefail.elliotfriend.com"
ORG_DESCRIPTION="A fun riff on the KALEpail project"
ORG_TWITTER="elliotfriend"
ORG_GITHUB="https://github.com/elliotfriend"

[[PRINCIPALS]]
name="Elliot Voris"
email="elliot@stellar.org"
discord="elliotfriend"
twitter="elliotfriend"
github="elliotfriend"
keybase="elliotfriend"

[[CURRENCIES]]
code="BROCCOLI"
issuer="GATWCHLKROX6LB2UJ6JM5VKMLLUKKQ5II6MAHFCKCEU47OYGIOENFAIL"
name="The Blockchain Tree Food"
desc="A cultivar of the ever-popular KALE asset, powered by Soroban"
image="https://kalefail.elliotfriend.com/assets/broccoli.png"

[[CURRENCIES]]
code="CABBAGE"
issuer="GATWCHLKROX6LB2UJ6JM5VKMLLUKKQ5II6MAHFCKCEU47OYGIOENFAIL"
name="The Blockchain Head Food"
desc="A cultivar of the ever-popular KALE asset, powered by Soroban"
image="https://kalefail.elliotfriend.com/assets/cabbage.png"

[[CURRENCIES]]
code="KOHLRABI"
issuer="GATWCHLKROX6LB2UJ6JM5VKMLLUKKQ5II6MAHFCKCEU47OYGIOENFAIL"
name="The Blockchain Turnip Food"
desc="A cultivar of the ever-popular KALE asset, powered by Soroban"
image="https://kalefail.elliotfriend.com/assets/kohlrabi.png"
